import type { Schemas } from "./parser.ts";

export const SCHEMAS: Schemas = {
  global: [
    { name: "session", short: "s", kind: "string" },
    { name: "json", kind: "boolean" },
    { name: "help", short: "h", kind: "boolean" },
  ],
  commands: [
    { name: "install",     positional: [],                                                   flags: [{ name: "force", short: "f", kind: "boolean" }] },
    { name: "open",        positional: [{ name: "url", required: false }],                   flags: [] },
    { name: "goto",        positional: [{ name: "url", required: true }],                    flags: [] },
    { name: "close",       positional: [{ name: "session", required: false }],               flags: [{ name: "all", kind: "boolean" }] },
    { name: "snapshot",    positional: [],                                                   flags: [{ name: "filename", kind: "string" }, { name: "depth", kind: "string" }] },
    { name: "click",       positional: [{ name: "ref", required: true }],                    flags: [] },
    { name: "fill",        positional: [{ name: "ref", required: true }, { name: "text", required: true }], flags: [] },
    { name: "type",        positional: [{ name: "text", required: true }],                   flags: [] },
    { name: "press",       positional: [{ name: "key", required: true }],                    flags: [] },
    { name: "hover",       positional: [{ name: "ref", required: true }],                    flags: [] },
    { name: "select",      positional: [{ name: "ref", required: true }, { name: "value", required: true }], flags: [] },
    { name: "check",       positional: [{ name: "ref", required: true }],                    flags: [] },
    { name: "uncheck",     positional: [{ name: "ref", required: true }],                    flags: [] },
    { name: "screenshot",  positional: [],                                                   flags: [{ name: "filename", kind: "string" }] },
    { name: "resize",      positional: [{ name: "width", required: true }, { name: "height", required: true }], flags: [] },
    { name: "go-back",     positional: [],                                                   flags: [] },
    { name: "go-forward",  positional: [],                                                   flags: [] },
    { name: "reload",      positional: [],                                                   flags: [] },
    { name: "list",        positional: [],                                                   flags: [] },
    { name: "localstorage-list",   positional: [],                                                                       flags: [] },
    { name: "localstorage-get",    positional: [{ name: "key", required: true }],                                        flags: [] },
    { name: "localstorage-set",    positional: [{ name: "key", required: true }, { name: "value", required: true }],     flags: [] },
    { name: "localstorage-delete", positional: [{ name: "key", required: true }],                                        flags: [] },
    { name: "localstorage-clear",  positional: [],                                                                       flags: [] },
    { name: "sessionstorage-list",   positional: [],                                                                       flags: [] },
    { name: "sessionstorage-get",    positional: [{ name: "key", required: true }],                                        flags: [] },
    { name: "sessionstorage-set",    positional: [{ name: "key", required: true }, { name: "value", required: true }],     flags: [] },
    { name: "sessionstorage-delete", positional: [{ name: "key", required: true }],                                        flags: [] },
    { name: "sessionstorage-clear",  positional: [],                                                                       flags: [] },
    { name: "eval",     positional: [{ name: "expression", required: true }],                                               flags: [] },
    { name: "run-code", positional: [{ name: "code", required: true }],                                                     flags: [] },
    {
      name: "cookie-list",
      positional: [],
      flags: [
        { name: "domain", kind: "string" },
        { name: "url",    kind: "string" },
      ],
    },
    {
      name: "cookie-get",
      positional: [{ name: "name", required: true }],
      flags: [
        { name: "domain", kind: "string" },
        { name: "url",    kind: "string" },
      ],
    },
    {
      name: "cookie-set",
      positional: [{ name: "name", required: true }, { name: "value", required: true }],
      flags: [
        { name: "domain",    kind: "string" },
        { name: "url",       kind: "string" },
        { name: "path",      kind: "string" },
        { name: "http-only", kind: "boolean" },
        { name: "secure",    kind: "boolean" },
        { name: "same-site", kind: "string" },
        { name: "expires",   kind: "string" },
      ],
    },
    {
      name: "cookie-delete",
      positional: [{ name: "name", required: true }],
      flags: [
        { name: "domain", kind: "string" },
        { name: "url",    kind: "string" },
        { name: "path",   kind: "string" },
      ],
    },
    { name: "cookie-clear", positional: [], flags: [] },
    { name: "state-save", positional: [{ name: "file", required: true }], flags: [] },
    { name: "state-load", positional: [{ name: "file", required: true }], flags: [] },
    { name: "mcp", positional: [], flags: [] },
  ],
};
